INSERT INTO Product(id, name, code) VALUES (1, 'TV', '123') ON CONFLICT DO NOTHING;
INSERT INTO Product(id, name, code) VALUES (2, 'MONITOR', '321') ON CONFLICT DO NOTHING;
INSERT INTO Product(id, name, code) VALUES (3, 'SOFA', '4321') ON CONFLICT DO NOTHING;
INSERT INTO Product(id, name, code) VALUES (4, 'LAPTOP', '1234') ON CONFLICT DO NOTHING;
INSERT INTO Product(id, name, code) VALUES (5, 'KEYBOARD', '54321') ON CONFLICT DO NOTHING;