server:
  port: 8888
spring:
  security:
    user:
      name: root
      password: root
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Reivals/test-config-repo.git
          clone-on-start: true